#!/bin/bash

. test_helper

BASE_DIR=/tmp/dad_test

### directory
if [ ! -d ${BASE_DIR}/post ]; then
    echo "directory: ${BASE_DIR}/post is not found."
    exit 1
fi

if [ -d ${BASE_DIR}/pre/a ]; then
    echo "directory: ${BASE_DIR}/pre/a exists yet."
    exit 1
fi

### file
if [ ! -e ${BASE_DIR}/foo ]; then
    echo "file: ${BASE_DIR}/foo is not found."
    exit 1
fi

if [ -e ${BASE_DIR}/pre/dummy ]; then
    echo "file: ${BASE_DIR}/pre/dummy exists yet."
    exit 1
fi

### git
if [ ! -e ${BASE_DIR}/dad/project.clj ]; then
    echo "git: ${BASE_DIR}/dad/project.clj is not found."
    exit 1
fi

### execute
if [ ! -e ${BASE_DIR}/hello ]; then
    echo "execute: ${BASE_DIR}/hello is not found."
    exit 1
fi

if [ -e ${BASE_DIR}/error ]; then
    echo "execute: ${BASE_DIR}/error exists."
    exit 1
fi

### link
if [ ! -L ${BASE_DIR}/world ]; then
    echo "link: ${BASE_DIR}/world is not a symbolic link."
    exit 1
fi

ls -l ${BASE_DIR}/world | grep "\-> ${BASE_DIR}/hello" > /dev/null 2>&1
if [ $? -ne 0 ]; then
    echo "link: ${BASE_DIR}/world's destrination is not ${BASE_DIR}/hello."
    exit 1
fi

### package
# install
helper_is_installed sl > /dev/null 2>&1
if [ $? -ne 0 ]; then
    echo "package: sl is not installed."
    exit 1
fi

# uninstall
helper_is_installed cowsay > /dev/null 2>&1
if [ $? -eq 0 ]; then
    echo "package: cowsay is installed yet."
    exit 1
fi

### template
if [ ! -e ${BASE_DIR}/tmpl ]; then
    echo "template: ${BASE_DIR}/tmpl is not found."
    exit 1
fi
helper_check_md5 template.md5 > /dev/null 2>&1
if [ $? -ne 0 ]; then
    echo "template: MD5 hash is not matched."
    exit 1
fi
