#!/bin/bash

. test_helper

BASE_DIR=/tmp/daddy_test

mkdir -p ${BASE_DIR}/pre/a/b/c/d
echo dummy > ${BASE_DIR}/pre/dummy

if [ ! -d ${BASE_DIR}/pre/a/b/c/d ]; then
    echo "pre: ${BASE_DIR}/pre/a/b/c/d is not found."
fi

if [ ! -e ${BASE_DIR}/pre/dummy ]; then
    echo "pre: ${BASE_DIR}/pre/dummy is not found."
    exit 1
fi

helper_is_installed sl > /dev/null 2>&1
if [ $? -eq 0 ]; then
    echo "pre: sl is already installed."
    exit 1
fi

helper_is_installed cowsay > /dev/null 2>&1
if [ $? -ne 0 ]; then
    helper_install_package cowsay > /dev/null 2>&1
    if [ $? -ne 0 ]; then
        echo "package: failed to pre-install cowsay."
        exit 1
    fi
fi
