#!/bin/bash

. test_helper

mkdir -p ${BASE_DIR}/pre/a/b/c/d
echo dummy > ${BASE_DIR}/pre/dummy

if [ ! -d ${BASE_DIR}/pre/a/b/c/d ]; then
    echo "pre: ${BASE_DIR}/pre/a/b/c/d is not found."
fi

if [ ! -e ${BASE_DIR}/pre/dummy ]; then
    echo "pre: ${BASE_DIR}/pre/dummy is not found."
    exit 1
fi

${DAD_CMD} --eval '(package ["git" "cowsay"])'
if [ $? -ne 0 ]; then
    echo "pre: failed to pre-install git or cowsay."
    exit 1
fi

${DAD_CMD} --eval '(package "sl" {:action :uninstall})'
if [ $? -ne 0 ]; then
    echo "pre: failed to pre-uninstall sl."
    exit 1
fi

helper_cleanup_package > /dev/null 2>&1
