#!/bin/bash

OS_TYPE="$(uname)"
BASE_DIR=/tmp/dad_test
DAD_CMD='dad'

ls -1 dad.linux-amd64 > /dev/null 2>&1
if [ $? -eq 0 ]; then
    DAD_CMD='./dad.linux-amd64'
else
    ls -1 dad > /dev/null 2>&1
    if [ $? -eq 0 ]; then
        DAD_CMD='./dad'
    else
        DAD_CMD='java -jar dad.jar'
    fi
fi

helper_is_installed () {
    if [ ${OS_TYPE} = 'Darwin' ]; then
        brew list ${1}
    else
        dpkg --status ${1} | grep -i status | grep -i installed
    fi
    return $?
}

helper_install_package() {
    RESULT=0
    if [ ${OS_TYPE} = 'Darwin' ]; then
        brew install -f ${1}
    else
        apt update
        apt install -y ${1}
    fi
    return $?
}

helper_cleanup_package() {
    if [ ${OS_TYPE} = 'Darwin' ]; then
        :
    else
        apt-get clean
        rm -rf /var/lib/apt/lists/*
    fi
    return $?
}

helper_uninstall_package() {
    if [ ${OS_TYPE} = 'Darwin' ]; then
        brew uninstall -f ${1}
    else
        apt remove -y ${1}
    fi
    return $?
}

helper_check_md5() {
    if [ ${OS_TYPE} = 'Darwin' ]; then
        helper_is_installed md5sha1sum
        if [ $? -ne 0 ]; then
            helper_install_package md5sha1sum
        fi
    fi
    md5sum -c ${1}
    return $?
}
