= Dad

image:https://github.com/liquidz/dad/workflows/test/badge.svg[link="https://github.com/liquidz/dad/actions"]
image:https://img.shields.io/github/release/liquidz/dad.svg?logo=Github[link="https://github.com/liquidz/dad/releases"]

> My father is a greate chef :)

Dad is a small configuration management tool for Clojure.
This project is heavily inspired by https://github.com/itamae-kitchen/mitamae[mitamae].

== Concept
- Easy to start -- Download single binary and run it.
- Minimum to remember -- May not write code for Dad often

== Getting Started

Download binary from https://github.com/liquidz/dad/releases[releases].
[source,terminal]
----
# Download latest dad to the current working directory
curl -L https://raw.githubusercontent.com/liquidz/dad/master/script/download | bash
./dad your_task.clj
----

Here is a example to install Clojure https://clojure.org/guides/deps_and_cli[command line tools].
[source,clojure]
----
#!/usr/bin/env dad --no-color --dry-run

(package ["curl" "rlwrap"])

;; You can define function as you like
(defn curl [m]
  (let [{:keys [path url]} m]
    ;; `file-exists?` is a built-in function in dad.
    (when (and (not (file-exists? path))
               (string? url))
      (execute (str "curl -sfLo " path " " url)))))

(curl {:path "/tmp/install.sh"
       :url "https://download.clojure.org/install/linux-install-1.10.1.489.sh"})

(file {:path "/tmp/install.sh" :mode "755"})
(execute {:cwd "/tmp" :command "./install.sh"})
(file {:path "/tmp/install.sh" :action :delete})
----

== Supports

- [x] Ubuntu (`apt`)
- [x] macOS (link:https://brew.sh[Homebrew])

== Example

- link:./example/vim[Building vim by source]
- link:./test/resources/test_task/tasks.clj[Test task]

== Reference

NOTE: You can refer all documents in *codes*. (evaluate `(dad/doc)` or `(help)`)

=== Built-in vars / functions

|===
| Name         | Var/Func | Description

| link:doc/dad_doc.adoc[dad/doc]         | Func | Print dad documents.
| link:doc/dad_env.adoc[dad/env]              | Var  | Map of environmental variables.
| dad/file-exists?                       | Func | Return true if the specified path exists.
| dad/os-type                            | Func | OS name string such as `"linux"` or `"mac"`.
| link:doc/dad_render.adoc[dad/render]   | Func | Render a template string with a data.
| link:doc/dad_doc.adoc[help] | Func | Alias for `dad/doc`.
| link:doc/dad_load_file.adoc[load-file] | Func | Load another recipe file.
|===

See https://github.com/borkdude/sci/blob/master/src/sci/impl/namespaces.cljc[sci/impl/namespaces.cljc] for other core functions.

=== Resources

Resources are called like follows.
`<main-arg>` will be associated to the main key for the resource.

[source,clojure]
----
(resource-name {:key :value ...})
(resource-name <main-arg> {:key :value ...})

;; E.g. following codes are equivalent because `directory` resource's main key is `path`.
(directory "foo/bar" {:owner "alice"})
(directory {:path "foo/bar" :owner "alice"})
----

|===
| Resource name | Description

| link:doc/directory.adoc[directory] | Create directories.
| link:doc/download.adoc[download] | Download a file from remote host.
| link:doc/execute.adoc[execute] | Execute a shell command.
| link:doc/file.adoc[file] | Create a file.
| link:doc/git.adoc[git] | Execute `git` command.
| link:doc/link.adoc[link] | Create a symbolic link.
| link:doc/package.adoc[package] | Install packages.
| link:doc/template.adoc[template] | Create a text file from the specified template files.

|===

== REPL

Dad also provides REPL mode that does not affect your environment. (same as `--dry-run` option)

[source,console]
----
$ dad --repl

user=> (println "hello from dad")
hello from dad
nil

user=> (+ 1 2 3)
6

user=> (package "sl")
apt-update [sl] ... will change
package-install [sl] ... will change

user=> (package "sl" {:action :uninstall})
package-uninstall [sl] ... WILL NOT change
----

== License

Copyright © 2019-2020 https://twitter.com/uochan[Masashi Iizuka]

This program and the accompanying materials are made available under the
terms of the Eclipse Public License 2.0 which is available at
http://www.eclipse.org/legal/epl-2.0.

This Source Code may also be made available under the following Secondary
Licenses when the conditions for such availability set forth in the Eclipse
Public License, v. 2.0 are satisfied: GNU General Public License as published by
the Free Software Foundation, either version 2 of the License, or (at your
option) any later version, with the GNU Classpath Exception which is available
at https://www.gnu.org/software/classpath/license.html.
// vim:fdm=marker:fdl=0
