#!/bin/bash

TMPDIR='./tmp'
IMAGE_NAME='clojure:openjdk-8-lein'
TARGET='target/daddy.jar'

mkdir -p ${TMPDIR}

\cp -pr test/resources/ubuntu/* ${TMPDIR}
\cp -pr ${TARGET} ${TMPDIR}

(cd ${TMPDIR} && docker run --rm -v $(pwd):/root ${IMAGE_NAME} bash /root/run.sh)

\rm -rf ${TMPDIR}
