#!/bin/bash

TMPDIR='./tmp'
#IMAGE_NAME='openjdk:11.0-jre-stretch'
IMAGE_NAME='clojure:openjdk-11-lein'

mkdir -p ${TMPDIR}

\cp -pr test/resources/ubuntu/* ${TMPDIR}
\cp -pr ${TARGET} ${TMPDIR}

(cd ${TMPDIR} && docker run --rm -v $(pwd):/root ${IMAGE_NAME} bash /root/run.sh)
#(cd ${TMPDIR} && docker run --rm -it -v $(pwd):/root ${IMAGE_NAME} bash)

\rm -rf ${TMPDIR}
