#!/bin/bash

TMPDIR='./tmp'
mkdir -p ${TMPDIR}

\cp -pr test/resources/test_task/* ${TMPDIR}
\cp -pr ${TARGET} ${TMPDIR}

(cd ${TMPDIR} && docker run --rm -v $(pwd):/root -w /root ${IMAGE_NAME} bash ./run.sh)
#(cd ${TMPDIR} && docker run --rm -it -v $(pwd):/root -w /root ${IMAGE_NAME} bash)

\rm -rf ${TMPDIR}
