#!/bin/bash

SCRIPT_DIR=$(cd $(dirname $0); pwd)
VERSION=$(cat ${SCRIPT_DIR}/../resources/version.txt | tr -d '"')

echo "version_check: Expected verion = ${VERSION}"

grep "== ${VERSION}" ${SCRIPT_DIR}/../CHANGELOG.adoc
if [ $? -ne 0 ]; then
    echo 'version_check: There is no corresponding section in CHANGELOG'
    exit 1
fi

exit 0
