name: lint
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeLaGuardo/setup-clj-kondo@master
        with:
          version: '2022.04.08'
      - run: clj-kondo --lint src:test --config '{:output {:pattern "::{{level}} file={{filename}},line={{row}},col={{col}}::{{message}}"}}'

  cljstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: 0918nobita/setup-cljstyle@v0.5.4
        with:
          cljstyle-version: 0.15.0
      - run: cljstyle check --report -v
