name: native_image
on:
  push:
    branches:
      - master
      - build-test
    tags:
      - '*'

jobs:
  linux-amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeLaGuardo/setup-clojure@master
        with:
          cli: latest
      - uses: actions/cache@v3
        with:
          path: |
            ~/.m2
            /tmp/.graalvm
          key: v1-linux-native-image-${{ hashFiles('Makefile', 'deps.edn') }}
      - name: Build native image
        run: make native-image
      - name: Run tests
        run: |
          cp -f dad test/resources/test_task/
          cd test/resources/test_task
          sudo bash run.sh
      - name: Rename
        run: mv dad dad.linux-amd64
      - uses: actions/upload-artifact@master
        with:
          name: dad.linux-amd64
          path: ./dad.linux-amd64

  darwin-amd64:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeLaGuardo/setup-clojure@master
        with:
          cli: latest
      - uses: actions/cache@v3
        with:
          path: |
            ~/.m2
            /tmp/.graalvm
          key: v1-mac-native-image-${{ hashFiles('Makefile', 'deps.edn') }}
      - name: Build native image
        run: make native-image
      - name: Run tests
        run: |
          cp -f dad test/resources/test_task/
          cd test/resources/test_task/
          bash run.sh
      - name: Rename
        run: mv dad dad.darwin-amd64
      - uses: actions/upload-artifact@master
        with:
          name: dad.darwin-amd64
          path: ./dad.darwin-amd64

  create-release:
    needs: [linux-amd64, darwin-amd64]
    if: contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            released
          draft: false
          prerelease: false

      - uses: actions/download-artifact@master
        with:
          name: dad.linux-amd64
          path: tmp
      - uses: actions/upload-release-asset@v1
        id: upload-linux-release-asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./tmp/dad.linux-amd64
          asset_name: dad.linux-amd64
          asset_content_type: application/octet-stream

      - uses: actions/download-artifact@master
        with:
          name: dad.darwin-amd64
          path: tmp
      - uses: actions/upload-release-asset@v1
        id: upload-darwin-release-asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./tmp/dad.darwin-amd64
          asset_name: dad.darwin-amd64
          asset_content_type: application/octet-stream
