name: test
on: [push]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: DeLaGuardo/setup-clojure@master
        with:
          cli: latest
      - uses: actions/cache@v1
        with:
          path: ~/.m2
          key: v1-linux-deps-${{ hashFiles('deps.edn') }}
      - run: make test
      # clojure command will not be found with `sudo`
      - run: make uberjar
      - run: sudo make local_jar_test

  darwin:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: DeLaGuardo/setup-clojure@master
        with:
          cli: latest
      - uses: actions/cache@v1
        with:
          path: ~/.m2
          key: v1-mac-deps-${{ hashFiles('deps.edn') }}
      - run: make test
      - run: make local_jar_test
